apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nl-lg
  namespace: cicd
  labels:
    nl_mode: lg
spec:
  replicas: 1
  metadata:
    labels:
      app: nl-lg
  selector:
    matchLabels:
      nl_mode: lg
  template:
    metadata:
      labels:
        nl_mode: lg
    spec:
      containers:
        env:
        - image: neotys/neoload-loadgenerator:latest
          name: nl-lg
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7100
        restartPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: nl-lg
  labels:
     app: nl-lg
     nl_mode: lg
  namespace: cicd
spec:
  ports:
    - name: NL
      protocol: TCP
      port: 7100
      targetPort: 7100
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
  selector:
    app: nl-lg
    service: nl-lg
  type: ClusterIP

