apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nl-lg
  name: nl-lg
spec:
  replicas: 1

  template:
    spec:
      containers:
      - image: neotys/neoload-loadgenerator:latest
        name: nl-lg
        ports:
          - containerPort: 7100
      restartPolicy: Always
