apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nl-lg
  namespace: cicd
  labels:
    nl_mode: slave
spec:
  replicas: 1
  metadata:
    labels:
      app: nl-lg
  selector:
    matchLabels:
      nl_mode: slave
  template:
    metadata:
      labels:
        nl_mode: slave
    spec:
      containers:
        env:
        - image: neotys/neoload-loadgenerator:latest
          name: nl-lg
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7100
        restartPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: nl-lg
  labels:
     app: nl-lg
     nl_mode: slave
  namespace: cicd
spec:
  ports:
  - name: lg
    port: 7100
    targetPort: 7100
  selector:
    app: nl-lg
    service: nl-lg
  type: ClusterIP
kind: Service
apiVersion: v1
metadata:
  name: nlweb
spec:
  type: ExternalName
  externalName: neoload-rest.saas.neotys.com
